name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ NEW Scripts'
    labels:
      - 'new script'
  - title: '🚀 UPDATED Scripts'
    labels:
      - 'update script'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug fix'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking change'
  minor:
    labels:
      - 'minor'
      - 'new script'
      - 'update script'
  patch:
    labels:
      - 'patch'
      - 'bug fix'
      - 'chore'
  default: patch
template: |
  ## What’s Changed

  $CHANGES